const valuationSnapshot = {
  asOf: "2026-06-09",
  source: "Market-data snapshot plus analyst qualitative classification",
  sourceCn: "市场数据快照叠加分析师定性分类",
  disclaimer:
    "Valuation bands are not price targets. Multiples can change intraday and should be refreshed before investment decisions.",
  disclaimerCn: "估值分组不是目标价。倍数会随市场实时变化，投资决策前应重新刷新。"
};

const valuationData = [
  { ticker: "NVDA", capTier: "Mega", pe: "31.8x", band: "Premium AI compounder", bandCn: "高溢价 AI 复合增长", read: "Premium multiple is supported by extreme data-center growth, but upside now depends on Rubin-cycle durability and margin resilience.", readCn: "高估值由极强数据中心增长支撑，但继续上行取决于 Rubin 周期持续性与利润率韧性。" },
  { ticker: "AVGO", capTier: "Mega", pe: "56.0x", band: "Premium compounder", bandCn: "高溢价复合增长", read: "Valuation reflects scarce custom-ASIC exposure plus VMware cash generation; watch customer concentration and XPU program timing.", readCn: "估值反映稀缺定制 ASIC 暴露和 VMware 现金流；需关注客户集中度与 XPU 项目节奏。" },
  { ticker: "MSFT", capTier: "Mega", pe: "36.4x", band: "Quality premium", bandCn: "优质龙头溢价", read: "A premium but diversified AI platform multiple, with Azure AI, Copilot and enterprise distribution reducing single-product risk.", readCn: "估值偏高但业务分散，Azure AI、Copilot 与企业分发降低单一产品风险。" },
  { ticker: "GOOGL", capTier: "Mega", pe: "20.3x", band: "Relative value AI", bandCn: "相对低估 AI 平台", read: "Lower multiple versus AI peers, but the market still discounts search disruption and capex intensity.", readCn: "相对 AI 同行估值较低，但市场仍折价搜索被颠覆风险和资本开支强度。" },
  { ticker: "AMZN", capTier: "Mega", pe: "35.7x", band: "Scale premium", bandCn: "规模平台溢价", read: "AWS AI capex and retail margin expansion both matter; valuation needs AWS acceleration to stay credible.", readCn: "AWS AI 资本开支与零售利润率扩张都重要；估值需要 AWS 再加速来支撑。" },
  { ticker: "META", capTier: "Mega", pe: "28.4x", band: "Cash-flow AI premium", bandCn: "现金流 AI 溢价", read: "Still cheaper than many AI infrastructure names; valuation debate centers on AI capex ROI and ad-product lift.", readCn: "仍低于许多 AI 基建股；估值核心在 AI 资本开支回报和广告产品提升。" },
  { ticker: "TSLA", capTier: "Mega", pe: "196.5x", band: "Optionality premium", bandCn: "期权型高溢价", read: "Multiple is dominated by autonomy and robotics optionality, not near-term auto earnings.", readCn: "估值主要由自动驾驶和机器人期权驱动，而非短期汽车盈利。" },
  { ticker: "TSM", capTier: "Mega", pe: "N.A.", band: "Strategic bottleneck premium", bandCn: "战略瓶颈溢价", read: "Valuation is justified by AI foundry scarcity, but geopolitics and capex cycles require a discount rate premium.", readCn: "AI 代工稀缺性支撑估值，但地缘政治与资本开支周期要求更高折现率。" },
  { ticker: "ASML", capTier: "Mega", pe: "N.A.", band: "Monopoly premium", bandCn: "垄断溢价", read: "Lithography monopoly deserves premium valuation; order cyclicality and China controls are the key swing factors.", readCn: "光刻垄断地位应享有溢价；订单周期和中国管制是关键变量。" },
  { ticker: "AMD", capTier: "Mega", pe: "98.3x", band: "High-expectation challenger", bandCn: "高预期挑战者", read: "Valuation prices major AI GPU share gains; the bar is now backlog conversion, not just product roadmap credibility.", readCn: "估值已计入 AI GPU 份额提升；关键从产品路线图变成订单兑现。" },
  { ticker: "ARM", capTier: "Large", pe: "N.A.", band: "Royalty runway premium", bandCn: "版税长坡溢价", read: "A long-duration IP asset with high multiple sensitivity to royalty growth and cloud penetration.", readCn: "长久期 IP 资产，估值对版税增长和云端渗透高度敏感。" },
  { ticker: "MRVL", capTier: "Large", pe: "N.M.", band: "High-beta AI silicon", bandCn: "高 beta AI 芯片", read: "Valuation relies on custom silicon and optical ramps; execution misses can compress the multiple quickly.", readCn: "估值依赖定制芯片和光互联放量；执行失误会快速压缩倍数。" },
  { ticker: "MU", capTier: "Large", pe: "22.0x", band: "Cyclical AI leverage", bandCn: "周期型 AI 杠杆", read: "HBM improves through-cycle quality, but memory stocks should still be valued with cycle risk in mind.", readCn: "HBM 改善跨周期质量，但存储股仍需按周期风险估值。" },
  { ticker: "AMAT", capTier: "Large", pe: "21.2x", band: "Equipment value-growth", bandCn: "设备价值成长", read: "Reasonable multiple for semi-cap exposure; upside depends on leading-edge and advanced packaging capex.", readCn: "半导体设备估值相对合理；上行取决于先进制程和先进封装资本开支。" },
  { ticker: "LRCX", capTier: "Large", pe: "25.2x", band: "Equipment cycle premium", bandCn: "设备周期溢价", read: "Multiple is not stretched if memory WFE recovery and AI-driven DRAM demand continue.", readCn: "若存储 WFE 复苏和 AI DRAM 需求持续，估值并不过分。" },
  { ticker: "KLAC", capTier: "Large", pe: "31.3x", band: "Quality equipment premium", bandCn: "优质设备溢价", read: "Process-control scarcity supports the premium; watch order normalization after strong AI demand.", readCn: "过程控制稀缺性支撑溢价；关注强 AI 需求后的订单正常化。" },
  { ticker: "SNPS", capTier: "Large", pe: "N.A.", band: "EDA scarcity premium", bandCn: "EDA 稀缺溢价", read: "High-quality recurring IP/EDA asset, but valuation leaves less room for integration or China weakness.", readCn: "高质量经常性 EDA/IP 资产，但估值对整合和中国弱势容错较低。" },
  { ticker: "CDNS", capTier: "Large", pe: "80.7x", band: "EDA scarcity premium", bandCn: "EDA 稀缺溢价", read: "AI chip complexity supports premium multiples; growth deceleration would be punished.", readCn: "AI 芯片复杂度支撑高倍数；增长放缓会被市场惩罚。" },
  { ticker: "ANET", capTier: "Large", pe: "55.3x", band: "Networking premium", bandCn: "网络溢价", read: "Premium valuation reflects Ethernet AI cluster share gains; risk is hyperscaler order lumpiness.", readCn: "高估值反映以太网 AI 集群份额提升；风险是云厂商订单波动。" },
  { ticker: "VRT", capTier: "Large", pe: "75.3x", band: "Power/cooling premium", bandCn: "电力液冷溢价", read: "The market prices Vertiv as a data-center bottleneck winner; backlog quality matters more than headline growth.", readCn: "市场将维谛定价为数据中心瓶颈赢家；订单质量比表面增长更重要。" },
  { ticker: "DELL", capTier: "Large", pe: "20.2x", band: "Server value-growth", bandCn: "服务器价值成长", read: "Lower multiple than pure AI names, reflecting hardware cyclicality and margin skepticism.", readCn: "估值低于纯 AI 标的，反映硬件周期性和利润率疑虑。" },
  { ticker: "SMCI", capTier: "Large", pe: "29.6x", band: "Execution-discounted AI server", bandCn: "执行折价 AI 服务器", read: "AI revenue is real, but governance, margin and customer concentration keep the risk premium high.", readCn: "AI 收入真实，但治理、利润率和客户集中度使风险溢价较高。" },
  { ticker: "HPE", capTier: "Large", pe: "22.2x", band: "Value AI server", bandCn: "价值型 AI 服务器", read: "Valuation is more reasonable, but the market needs proof that AI systems can lift margins sustainably.", readCn: "估值更合理，但市场需要看到 AI 系统持续提升利润率的证据。" },
  { ticker: "ORCL", capTier: "Mega", pe: "58.4x", band: "AI cloud premium", bandCn: "AI 云溢价", read: "Backlog-driven rerating is powerful; valuation risk rises if OCI capacity monetization slips.", readCn: "积压订单驱动重估强劲；若 OCI 产能变现延迟，估值风险上升。" },
  { ticker: "CRM", capTier: "Large", pe: "36.4x", band: "Enterprise AI quality", bandCn: "企业 AI 优质估值", read: "Multiple is fair if Agentforce can lift growth; otherwise buybacks and margin support dominate.", readCn: "若 Agentforce 能提升增长，估值合理；否则主要靠回购和利润率支撑。" },
  { ticker: "PLTR", capTier: "Large", pe: "215.7x", band: "Narrative premium", bandCn: "叙事型高溢价", read: "AIP demand is strong, but valuation requires exceptional durability and operating leverage.", readCn: "AIP 需求强劲，但估值要求极高增长持续性和经营杠杆。" },
  { ticker: "SNOW", capTier: "Large", pe: "N.M.", band: "Growth re-acceleration bet", bandCn: "增长再加速赌注", read: "Valuation depends on AI data workload acceleration and operating leverage after heavy investment.", readCn: "估值取决于 AI 数据负载再加速以及重投入后的经营杠杆。" },
  { ticker: "NOW", capTier: "Large", pe: "120.6x", band: "Workflow premium", bandCn: "工作流平台溢价", read: "Premium is justified by workflow control and AI attach, but expectations are demanding.", readCn: "工作流控制点和 AI 附加率支撑溢价，但市场预期很高。" },
  { ticker: "CRWD", capTier: "Large", pe: "N.A.", band: "Security AI premium", bandCn: "安全 AI 溢价", read: "Valuation depends on platform consolidation and trust recovery translating into net retention.", readCn: "估值取决于平台整合和信任修复能否转化为净留存。" },
  { ticker: "DDOG", capTier: "Large", pe: "429.3x", band: "Observability premium", bandCn: "可观测性溢价", read: "AI workloads support usage growth, but high multiple leaves little margin for consumption softness.", readCn: "AI 工作负载支撑用量增长，但高倍数对消费疲软容错很低。" },
  { ticker: "NET", capTier: "Large", pe: "N.M.", band: "Edge AI premium", bandCn: "边缘 AI 溢价", read: "The market pays for edge network optionality; monetization must catch up to the narrative.", readCn: "市场为边缘网络期权付费；商业化需要跟上叙事。" },
  { ticker: "APP", capTier: "Large", pe: "70.8x", band: "AI ad-tech premium", bandCn: "AI 广告技术溢价", read: "Valuation reflects proven AI monetization; concentration and regulatory risk are the offsets.", readCn: "估值反映已验证的 AI 商业化；集中度和监管是抵消因素。" },
  { ticker: "TTD", capTier: "Large", pe: "124.3x", band: "Ad-tech premium", bandCn: "广告技术溢价", read: "Premium multiple needs sustained CTV and Kokai monetization despite macro sensitivity.", readCn: "高估值需要 CTV 和 Kokai 持续变现，同时承受宏观敏感性。" },
  { ticker: "ETN", capTier: "Large", pe: "38.9x", band: "Electrification premium", bandCn: "电气化溢价", read: "Valuation reflects data-center electrical scarcity; order growth and margins must stay strong.", readCn: "估值反映数据中心电气设备稀缺；订单增长和利润率需保持强劲。" },
  { ticker: "GEV", capTier: "Large", pe: "108.9x", band: "Power scarcity premium", bandCn: "电力稀缺溢价", read: "Turbine and grid scarcity justify rerating, but valuation now discounts years of execution.", readCn: "燃机和电网稀缺支撑重估，但估值已经计入多年执行。" },
  { ticker: "PWR", capTier: "Large", pe: "62.8x", band: "Grid buildout premium", bandCn: "电网建设溢价", read: "Premium reflects visible utility and data-center work; labor availability is a valuation risk.", readCn: "高估值反映公用事业和数据中心工程可见度；劳动力供给是估值风险。" },
  { ticker: "SOUN", capTier: "Mid", pe: "N.M.", band: "Speculative optionality", bandCn: "投机期权", read: "Valuation is revenue-multiple and narrative driven; position sizing should reflect execution risk.", readCn: "估值由收入倍数和叙事驱动；仓位应反映执行风险。" },
  { ticker: "BBAI", capTier: "Small", pe: "N.M.", band: "Speculative optionality", bandCn: "投机期权", read: "Defense AI optionality is interesting, but small scale and losses make valuation fragile.", readCn: "国防 AI 期权有吸引力，但规模小和亏损使估值脆弱。" },
  { ticker: "IONQ", capTier: "Large", pe: "N.M.", band: "Frontier optionality", bandCn: "前沿期权", read: "Quantum valuation is option-like and highly sensitive to milestones rather than current revenue.", readCn: "量子估值类似期权，高度取决于里程碑而非当前收入。" },
  { ticker: "RGTI", capTier: "Mid", pe: "N.M.", band: "Frontier optionality", bandCn: "前沿期权", read: "Very high-risk quantum exposure; valuation can move sharply with funding and technical milestones.", readCn: "高风险量子暴露；估值会随融资和技术里程碑剧烈波动。" },
  { ticker: "PATH", capTier: "Mid", pe: "N.M.", band: "Turnaround AI software", bandCn: "转型型 AI 软件", read: "Valuation needs credible agentic automation growth after several years of deceleration.", readCn: "估值需要在多年放缓后看到可信的 Agent 自动化增长。" },
  { ticker: "ISRG", capTier: "Large", pe: "65.8x", band: "Medtech quality premium", bandCn: "医疗科技优质溢价", read: "Premium reflects durable procedure growth and installed-base economics, not pure AI hype.", readCn: "溢价来自手术量增长和装机生态，而不是纯 AI 炒作。" },
  { ticker: "MBLY", capTier: "Mid", pe: "N.M.", band: "Autonomy reset", bandCn: "自动驾驶重估", read: "Valuation remains dependent on design wins and recovery in auto ADAS demand.", readCn: "估值仍取决于车型定点和汽车 ADAS 需求修复。" },
  { ticker: "CEG", capTier: "Large", pe: "38.6x", band: "Nuclear scarcity premium", bandCn: "核电稀缺溢价", read: "Power scarcity and nuclear contracts support premium valuation; merchant power risk remains.", readCn: "电力稀缺和核电长期合同支撑溢价；商用电价风险仍在。" },
  { ticker: "VST", capTier: "Large", pe: "36.9x", band: "Power scarcity premium", bandCn: "电力稀缺溢价", read: "AI power demand has rerated the stock; valuation is sensitive to power price assumptions.", readCn: "AI 电力需求推动重估；估值对电价假设非常敏感。" },
  { ticker: "OKLO", capTier: "Mid", pe: "N.M.", band: "Speculative nuclear optionality", bandCn: "投机型核电期权", read: "Pre-commercial nuclear exposure with long-duration optionality and binary regulatory risk.", readCn: "商业化前核电标的，久期期权大，同时监管二元风险高。" },
  { ticker: "BWXT", capTier: "Large", pe: "N.A.", band: "Defense nuclear premium", bandCn: "国防核能溢价", read: "Valuation is supported by defense nuclear backlog plus AI-power adjacency.", readCn: "国防核能积压订单和 AI 电力相关性支撑估值。" },
  { ticker: "HUBB", capTier: "Large", pe: "32.7x", band: "Grid equipment premium", bandCn: "电网设备溢价", read: "Grid upgrade scarcity supports a premium industrial multiple.", readCn: "电网升级稀缺性支撑工业股溢价倍数。" },
  { ticker: "FIX", capTier: "Large", pe: "45.8x", band: "Data-center services premium", bandCn: "数据中心服务溢价", read: "High multiple reflects mechanical/electrical bottleneck exposure; labor execution matters.", readCn: "高倍数反映机电工程瓶颈暴露；劳动力执行很重要。" },
  { ticker: "INTC", capTier: "Large", pe: "N.M.", band: "Turnaround option", bandCn: "转型期权", read: "Valuation is asset-backed turnaround plus foundry optionality, not current AI leadership.", readCn: "估值来自资产型转型和代工期权，而非当前 AI 领先地位。" },
  { ticker: "QCOM", capTier: "Large", pe: "17.3x", band: "Reasonable edge AI", bandCn: "合理估值边缘 AI", read: "Lower multiple reflects handset cyclicality, partly offset by edge AI and auto diversification.", readCn: "较低倍数反映手机周期性，由边缘 AI 和汽车多元化部分抵消。" },
  { ticker: "ALAB", capTier: "Large", pe: "N.A.", band: "Connectivity premium", bandCn: "互联芯片溢价", read: "Valuation prices rare CXL/connectivity exposure; execution bar is high.", readCn: "估值反映稀缺 CXL/互联暴露；执行门槛很高。" },
  { ticker: "WDC", capTier: "Large", pe: "27.7x", band: "Storage cycle leverage", bandCn: "存储周期杠杆", read: "Valuation depends on NAND/HDD pricing and AI storage demand staying firm.", readCn: "估值取决于 NAND/HDD 价格和 AI 存储需求持续强劲。" },
  { ticker: "STX", capTier: "Large", pe: "34.2x", band: "Storage cycle premium", bandCn: "存储周期溢价", read: "AI nearline storage demand supports the rerating; watch pricing discipline.", readCn: "AI 近线存储需求支撑重估；关注价格纪律。" },
  { ticker: "GFS", capTier: "Large", pe: "N.M.", band: "Specialty foundry value", bandCn: "特色代工价值", read: "Not leading-edge AI, but useful for power, RF and specialty silicon exposure.", readCn: "不是先进 AI 代工，但在功率、射频和特色芯片上有价值。" },
  { ticker: "UMC", capTier: "Large", pe: "13.0x", band: "Mature-node value", bandCn: "成熟制程价值", read: "Low multiple reflects mature-node cyclicality; AI benefit is indirect.", readCn: "低估值反映成熟制程周期性；AI 受益较间接。" },
  { ticker: "STM", capTier: "Large", pe: "52.6x", band: "Cyclical semis reset", bandCn: "周期半导体重估", read: "Valuation needs industrial and auto semiconductor recovery before AI adjacency matters.", readCn: "估值需要工控和汽车半导体复苏，AI 相关性才会更有意义。" },
  { ticker: "COHR", capTier: "Large", pe: "N.A.", band: "Optical AI premium", bandCn: "光互联 AI 溢价", read: "AI optical demand supports upside, but the company must convert demand into margins.", readCn: "AI 光互联需求支撑上行，但公司必须把需求转化为利润率。" },
  { ticker: "LITE", capTier: "Mid", pe: "N.M.", band: "Optical turnaround", bandCn: "光通信转型", read: "Valuation is a recovery call on datacom optical modules and margin normalization.", readCn: "估值是对数通光模块复苏和利润率正常化的押注。" },
  { ticker: "CSCO", capTier: "Large", pe: "27.5x", band: "Value networking AI", bandCn: "价值型网络 AI", read: "Lower-multiple way to own networking and security, with AI upside less pure but less risky.", readCn: "以较低倍数持有网络和安全，AI 纯度较低但风险也更低。" },
  { ticker: "CIEN", capTier: "Mid", pe: "144.5x", band: "Optical cycle premium", bandCn: "光网络周期溢价", read: "Valuation anticipates optical demand recovery from cloud and AI traffic.", readCn: "估值预期云和 AI 流量带动光网络需求复苏。" },
  { ticker: "EQIX", capTier: "Large", pe: "95.9x", band: "Data-center real asset premium", bandCn: "数据中心实物资产溢价", read: "Premium REIT-like valuation reflects scarce interconnection assets and AI colocation demand.", readCn: "类 REIT 高估值反映稀缺互联资产和 AI 托管需求。" },
  { ticker: "DLR", capTier: "Large", pe: "45.9x", band: "Data-center REIT premium", bandCn: "数据中心 REIT 溢价", read: "Valuation is supported by AI leasing demand, but financing costs remain important.", readCn: "AI 租赁需求支撑估值，但融资成本仍重要。" },
  { ticker: "IBM", capTier: "Large", pe: "24.7x", band: "Reasonable enterprise AI", bandCn: "合理估值企业 AI", read: "Lower-risk enterprise AI and hybrid-cloud exposure at a moderate multiple.", readCn: "以适中倍数持有较低风险企业 AI 和混合云暴露。" },
  { ticker: "ADBE", capTier: "Large", pe: "24.4x", band: "Creative AI value", bandCn: "创意 AI 价值", read: "Multiple has compressed; upside depends on Firefly monetization and seat expansion.", readCn: "估值已压缩；上行取决于 Firefly 变现和席位扩张。" },
  { ticker: "SAP", capTier: "Large", pe: "48.8x", band: "Enterprise software premium", bandCn: "企业软件溢价", read: "Premium reflects cloud migration and embedded AI in core enterprise workflows.", readCn: "溢价反映云迁移和核心企业流程中的嵌入式 AI。" },
  { ticker: "BABA", capTier: "Large", pe: "N.A.", band: "China AI value", bandCn: "中国 AI 价值", read: "Lower valuation versus U.S. cloud peers reflects China macro, regulation and geopolitical discount.", readCn: "相对美国云同行估值较低，反映中国宏观、监管和地缘折价。" },
  { ticker: "BIDU", capTier: "Large", pe: "N.A.", band: "China AI turnaround", bandCn: "中国 AI 转型", read: "AI cloud and model progress compete with search pressure and China risk premium.", readCn: "AI 云和模型进展与搜索压力、中国风险溢价相互拉扯。" }
];

const additionalSources = [
  { id: "ceg-ir", name: "Constellation Energy Investor Relations", nameCn: "Constellation Energy 投资者关系", url: "https://investors.constellationenergy.com/" },
  { id: "vst-ir", name: "Vistra Investor Relations", nameCn: "Vistra 投资者关系", url: "https://investor.vistracorp.com/" },
  { id: "oklo-ir", name: "Oklo Investor Relations", nameCn: "Oklo 投资者关系", url: "https://investors.oklo.com/" },
  { id: "bwxt-ir", name: "BWX Technologies Investor Relations", nameCn: "BWXT 投资者关系", url: "https://investors.bwxt.com/" },
  { id: "hubb-ir", name: "Hubbell Investor Relations", nameCn: "Hubbell 投资者关系", url: "https://investors.hubbell.com/" },
  { id: "fix-ir", name: "Comfort Systems USA Investor Relations", nameCn: "Comfort Systems USA 投资者关系", url: "https://investors.comfortsystemsusa.com/" },
  { id: "intc-ir", name: "Intel Investor Relations", nameCn: "英特尔投资者关系", url: "https://www.intc.com/" },
  { id: "qcom-ir", name: "Qualcomm Investor Relations", nameCn: "高通投资者关系", url: "https://investor.qualcomm.com/financial-information/quarterly-results" },
  { id: "alab-ir", name: "Astera Labs Investor Relations", nameCn: "Astera Labs 投资者关系", url: "https://investors.asteralabs.com/" },
  { id: "wdc-ir", name: "Western Digital Investor Relations", nameCn: "西部数据投资者关系", url: "https://investor.wdc.com/" },
  { id: "stx-ir", name: "Seagate Investor Relations", nameCn: "希捷投资者关系", url: "https://investors.seagate.com/" },
  { id: "gfs-ir", name: "GlobalFoundries Investor Relations", nameCn: "格芯投资者关系", url: "https://investors.gf.com/" },
  { id: "umc-ir", name: "UMC Investor Relations", nameCn: "联电投资者关系", url: "https://www.umc.com/en/IR" },
  { id: "stm-ir", name: "STMicroelectronics Investor Relations", nameCn: "意法半导体投资者关系", url: "https://investors.st.com/" },
  { id: "cohr-ir", name: "Coherent Investor Relations", nameCn: "Coherent 投资者关系", url: "https://investors.coherent.com/" },
  { id: "lite-ir", name: "Lumentum Investor Relations", nameCn: "Lumentum 投资者关系", url: "https://investor.lumentum.com/" },
  { id: "csco-ir", name: "Cisco Investor Relations", nameCn: "思科投资者关系", url: "https://investor.cisco.com/" },
  { id: "cien-ir", name: "Ciena Investor Relations", nameCn: "Ciena 投资者关系", url: "https://investor.ciena.com/" },
  { id: "eqix-ir", name: "Equinix Investor Relations", nameCn: "Equinix 投资者关系", url: "https://investor.equinix.com/" },
  { id: "dlr-ir", name: "Digital Realty Investor Relations", nameCn: "Digital Realty 投资者关系", url: "https://investor.digitalrealty.com/" },
  { id: "ibm-ir", name: "IBM Investor Relations", nameCn: "IBM 投资者关系", url: "https://www.ibm.com/investor/" },
  { id: "adbe-ir", name: "Adobe Investor Relations", nameCn: "Adobe 投资者关系", url: "https://www.adobe.com/investor-relations.html" },
  { id: "sap-ir", name: "SAP Investor Relations", nameCn: "SAP 投资者关系", url: "https://www.sap.com/investors/en.html" },
  { id: "baba-ir", name: "Alibaba Quarterly Results", nameCn: "阿里巴巴季度业绩", url: "https://www.alibabagroup.com/en-US/ir-financial-reports-quarterly-results" },
  { id: "bidu-ir", name: "Baidu Quarterly Results", nameCn: "百度季度业绩", url: "https://ir.baidu.com/financial-information/quarterly-results" }
];

const additionalCompanies = [
  {
    id: "ceg",
    ticker: "CEG",
    company: "Constellation Energy",
    companyCn: "Constellation Energy",
    market: "US",
    layer: "energy-grid",
    type: "Core",
    conviction: "High",
    valuationRisk: "High",
    score: 86,
    role: "Largest U.S. nuclear operator and key zero-carbon power supplier for AI data centers.",
    roleCn: "美国最大核电运营商，也是 AI 数据中心零碳电力的重要供应商。",
    lastReport: "2026-05-06",
    nextWindow: "Early Aug 2026, estimated",
    financials: "Latest investor materials frame nuclear output and long-duration power contracting as the core earnings drivers.",
    financialsCn: "最新投资者材料显示，核电出力和长期电力合同是核心盈利驱动。",
    aiRead: "A direct electricity bottleneck beneficiary as hyperscalers seek large clean baseload power.",
    aiReadCn: "云厂商寻找大规模清洁基荷电力时，CEG 是直接电力瓶颈受益者。",
    catalysts: ["Nuclear PPA announcements", "Capacity price resets", "Data-center power contracting"],
    catalystsCn: ["核电 PPA 公告", "容量价格重置", "数据中心电力合同"],
    risks: ["Power price volatility", "Regulatory risk", "Nuclear operating events"],
    risksCn: ["电价波动", "监管风险", "核电运营事件"],
    sourceIds: ["ceg-ir"]
  },
  {
    id: "vst",
    ticker: "VST",
    company: "Vistra",
    companyCn: "Vistra",
    market: "US",
    layer: "energy-grid",
    type: "Core",
    conviction: "High",
    valuationRisk: "High",
    score: 84,
    role: "Power generation and retail electricity platform with nuclear and gas exposure.",
    roleCn: "电力发电与售电平台，拥有核电和天然气发电暴露。",
    lastReport: "2026-05-07",
    nextWindow: "Early Aug 2026, estimated",
    financials: "Power-market tightness and generation portfolio economics are the main earnings swing factors.",
    financialsCn: "电力市场紧张和发电组合经济性是主要盈利变量。",
    aiRead: "AI load growth increases scarcity value of dispatchable power.",
    aiReadCn: "AI 负荷增长提升可调度电力资产的稀缺价值。",
    catalysts: ["Power price strength", "Nuclear fleet value", "Data-center demand"],
    catalystsCn: ["电价强势", "核电资产价值", "数据中心需求"],
    risks: ["Commodity exposure", "Policy intervention", "Weather demand volatility"],
    risksCn: ["商品价格暴露", "政策干预", "天气需求波动"],
    sourceIds: ["vst-ir"]
  },
  {
    id: "oklo",
    ticker: "OKLO",
    company: "Oklo",
    companyCn: "Oklo",
    market: "US",
    layer: "energy-grid",
    type: "Speculative",
    conviction: "Low",
    valuationRisk: "Very High",
    score: 62,
    role: "Advanced nuclear developer targeting compact reactors for industrial and data-center power.",
    roleCn: "先进核能开发商，目标是为工业与数据中心提供小型反应堆电力。",
    lastReport: "2026-05-13",
    nextWindow: "Mid-Aug 2026, estimated",
    financials: "Still pre-commercial; valuation is driven by licensing, partnerships and project milestones rather than revenue.",
    financialsCn: "仍处商业化前阶段；估值主要由许可、合作伙伴和项目里程碑驱动，而非收入。",
    aiRead: "A high-optionality way to express long-term AI power demand.",
    aiReadCn: "表达长期 AI 电力需求的高期权标的。",
    catalysts: ["NRC milestones", "Power offtake deals", "Project financing"],
    catalystsCn: ["NRC 里程碑", "购电协议", "项目融资"],
    risks: ["Licensing delays", "Funding dilution", "Commercialization timeline"],
    risksCn: ["许可延迟", "融资摊薄", "商业化时间表"],
    sourceIds: ["oklo-ir"]
  },
  {
    id: "bwxt",
    ticker: "BWXT",
    company: "BWX Technologies",
    companyCn: "BWXT",
    market: "US",
    layer: "energy-grid",
    type: "Watchlist",
    conviction: "Medium",
    valuationRisk: "Medium",
    score: 76,
    role: "Nuclear components, fuel and defense nuclear systems.",
    roleCn: "核能部件、燃料与国防核系统。",
    lastReport: "2026-05-05",
    nextWindow: "Early Aug 2026, estimated",
    financials: "Backlog and defense nuclear demand provide higher visibility than most speculative nuclear names.",
    financialsCn: "积压订单和国防核能需求让其可见度高于多数投机型核能公司。",
    aiRead: "Indirect AI power exposure through nuclear supply-chain capability.",
    aiReadCn: "通过核能供应链能力间接受益于 AI 电力需求。",
    catalysts: ["Nuclear supply-chain spending", "Defense programs", "Advanced reactor activity"],
    catalystsCn: ["核供应链支出", "国防项目", "先进反应堆活动"],
    risks: ["Program timing", "Government budget risk", "Industrial execution"],
    risksCn: ["项目节奏", "政府预算风险", "工业执行"],
    sourceIds: ["bwxt-ir"]
  },
  {
    id: "hubb",
    ticker: "HUBB",
    company: "Hubbell",
    companyCn: "Hubbell",
    market: "US",
    layer: "energy-grid",
    type: "Watchlist",
    conviction: "Medium",
    valuationRisk: "Medium",
    score: 78,
    role: "Grid, utility and electrical infrastructure equipment.",
    roleCn: "电网、公用事业与电气基础设施设备。",
    lastReport: "2026-04-29",
    nextWindow: "Late Jul 2026, estimated",
    financials: "Utility and grid modernization demand are the key operating indicators.",
    financialsCn: "公用事业和电网现代化需求是关键经营指标。",
    aiRead: "Benefits from grid upgrades required by AI data-center load growth.",
    aiReadCn: "受益于 AI 数据中心负荷增长带来的电网升级需求。",
    catalysts: ["Utility capex", "Grid-hardening projects", "Electrical equipment pricing"],
    catalystsCn: ["公用事业资本开支", "电网加固项目", "电气设备定价"],
    risks: ["Industrial cycle", "Input costs", "Utility budget timing"],
    risksCn: ["工业周期", "投入成本", "公用事业预算节奏"],
    sourceIds: ["hubb-ir"]
  },
  {
    id: "fix",
    ticker: "FIX",
    company: "Comfort Systems USA",
    companyCn: "Comfort Systems USA",
    market: "US",
    layer: "energy-grid",
    type: "Watchlist",
    conviction: "Medium",
    valuationRisk: "High",
    score: 80,
    role: "Mechanical, electrical and HVAC contractor for large commercial and data-center projects.",
    roleCn: "大型商业和数据中心项目的机电、暖通和电气承包商。",
    lastReport: "2026-04-24",
    nextWindow: "Late Jul 2026, estimated",
    financials: "Backlog quality and data-center project mix are the core watch items.",
    financialsCn: "积压订单质量和数据中心项目占比是核心观察点。",
    aiRead: "Picks-and-shovels exposure to physical AI infrastructure buildout.",
    aiReadCn: "数据中心物理建设的“卖铲子”受益标的。",
    catalysts: ["Data-center backlog", "Margin execution", "Labor capacity"],
    catalystsCn: ["数据中心积压订单", "利润率执行", "劳动力产能"],
    risks: ["Project execution", "Labor shortages", "Multiple compression"],
    risksCn: ["项目执行", "劳动力短缺", "估值压缩"],
    sourceIds: ["fix-ir"]
  },
  {
    id: "intc",
    ticker: "INTC",
    company: "Intel",
    companyCn: "英特尔",
    market: "US",
    layer: "silicon",
    type: "Watchlist",
    conviction: "Low",
    valuationRisk: "High",
    score: 68,
    role: "CPU supplier and foundry turnaround candidate.",
    roleCn: "CPU 供应商和晶圆代工转型候选。",
    lastReport: "2026-04-24",
    nextWindow: "Late Jul 2026, estimated",
    financials: "The valuation case depends on foundry execution, cost restructuring and server CPU stabilization.",
    financialsCn: "估值取决于代工执行、成本重组和服务器 CPU 稳定。",
    aiRead: "Important strategically, but AI accelerator share remains limited versus NVIDIA/AMD/custom ASICs.",
    aiReadCn: "战略地位重要，但 AI 加速器份额仍落后于 NVIDIA、AMD 和定制 ASIC。",
    catalysts: ["Foundry customer wins", "Cost cuts", "Server CPU recovery"],
    catalystsCn: ["代工客户", "成本削减", "服务器 CPU 修复"],
    risks: ["Execution delays", "Capex intensity", "Competitive pressure"],
    risksCn: ["执行延迟", "资本开支强度", "竞争压力"],
    sourceIds: ["intc-ir"]
  },
  {
    id: "qcom",
    ticker: "QCOM",
    company: "Qualcomm",
    companyCn: "高通",
    market: "US",
    layer: "silicon",
    type: "Core",
    conviction: "Medium",
    valuationRisk: "Medium",
    score: 82,
    role: "Mobile, edge AI, automotive and connectivity silicon.",
    roleCn: "移动、边缘 AI、汽车与连接芯片。",
    lastReport: "2026-04-30",
    nextWindow: "Late Jul 2026, estimated",
    financials: "Handset cycle, licensing and auto/IoT diversification drive the near-term model.",
    financialsCn: "手机周期、授权业务和汽车/IoT 多元化驱动短期模型。",
    aiRead: "A key edge AI beneficiary as models move into phones, PCs, cars and devices.",
    aiReadCn: "随着模型进入手机、PC、汽车和终端，高通是关键边缘 AI 受益者。",
    catalysts: ["AI smartphone cycle", "Automotive pipeline", "PC/edge adoption"],
    catalystsCn: ["AI 手机周期", "汽车订单管线", "PC/边缘采用"],
    risks: ["Apple modem exposure", "Handset cyclicality", "China competition"],
    risksCn: ["苹果基带风险", "手机周期", "中国竞争"],
    sourceIds: ["qcom-ir"]
  },
  {
    id: "alab",
    ticker: "ALAB",
    company: "Astera Labs",
    companyCn: "Astera Labs",
    market: "US",
    layer: "datacenter",
    type: "Watchlist",
    conviction: "Medium",
    valuationRisk: "Very High",
    score: 79,
    role: "Connectivity semiconductors for AI and cloud infrastructure, including PCIe/CXL products.",
    roleCn: "面向 AI 与云基础设施的互联芯片，包括 PCIe/CXL 产品。",
    lastReport: "2026-05-06",
    nextWindow: "Early Aug 2026, estimated",
    financials: "Growth is tied to AI platform connectivity content and new product ramps.",
    financialsCn: "增长与 AI 平台互联内容和新产品放量相关。",
    aiRead: "Direct beneficiary of increasingly complex accelerator clusters.",
    aiReadCn: "直接受益于加速器集群复杂度提升。",
    catalysts: ["CXL adoption", "Hyperscaler platforms", "New connectivity products"],
    catalystsCn: ["CXL 采用", "云厂商平台", "新互联产品"],
    risks: ["Customer concentration", "Very high expectations", "Product-cycle risk"],
    risksCn: ["客户集中度", "极高预期", "产品周期风险"],
    sourceIds: ["alab-ir"]
  },
  {
    id: "wdc",
    ticker: "WDC",
    company: "Western Digital",
    companyCn: "西部数据",
    market: "US",
    layer: "silicon",
    type: "Watchlist",
    conviction: "Medium",
    valuationRisk: "Medium",
    score: 76,
    role: "HDD and flash storage supplier for cloud and data-center workloads.",
    roleCn: "云和数据中心工作负载的 HDD 与闪存供应商。",
    lastReport: "2026-04-30",
    nextWindow: "Late Jul 2026, estimated",
    financials: "Storage pricing and cloud demand are the main earnings drivers.",
    financialsCn: "存储价格和云需求是主要盈利驱动。",
    aiRead: "AI training and inference create growing cold/warm storage demand beyond GPUs.",
    aiReadCn: "AI 训练与推理在 GPU 之外也带来冷/温数据存储需求。",
    catalysts: ["Cloud storage demand", "NAND pricing", "HDD capacity cycle"],
    catalystsCn: ["云存储需求", "NAND 价格", "HDD 容量周期"],
    risks: ["Storage downturn", "Pricing discipline", "Product mix"],
    risksCn: ["存储下行周期", "价格纪律", "产品结构"],
    sourceIds: ["wdc-ir"]
  },
  {
    id: "stx",
    ticker: "STX",
    company: "Seagate Technology",
    companyCn: "希捷科技",
    market: "US",
    layer: "silicon",
    type: "Watchlist",
    conviction: "Medium",
    valuationRisk: "Medium",
    score: 75,
    role: "Nearline HDD supplier for cloud, data-center and AI storage.",
    roleCn: "面向云、数据中心和 AI 存储的近线 HDD 供应商。",
    lastReport: "2026-04-29",
    nextWindow: "Late Jul 2026, estimated",
    financials: "Nearline demand and HAMR transition are the core operating drivers.",
    financialsCn: "近线需求和 HAMR 转换是核心经营驱动。",
    aiRead: "AI data growth supports long-term storage demand, but pricing cycles remain important.",
    aiReadCn: "AI 数据增长支撑长期存储需求，但价格周期仍重要。",
    catalysts: ["Nearline demand", "HAMR ramp", "Cloud inventory rebuild"],
    catalystsCn: ["近线需求", "HAMR 放量", "云库存重建"],
    risks: ["Cyclical pricing", "Customer inventory", "Technology transition"],
    risksCn: ["周期价格", "客户库存", "技术转换"],
    sourceIds: ["stx-ir"]
  },
  {
    id: "gfs",
    ticker: "GFS",
    company: "GlobalFoundries",
    companyCn: "格芯",
    market: "US",
    layer: "semicap",
    type: "Watchlist",
    conviction: "Medium",
    valuationRisk: "Medium",
    score: 72,
    role: "Specialty foundry for RF, power, automotive and embedded silicon.",
    roleCn: "射频、功率、汽车和嵌入式芯片特色代工厂。",
    lastReport: "2026-05-06",
    nextWindow: "Early Aug 2026, estimated",
    financials: "Revenue recovery depends on automotive/industrial demand and long-term supply agreements.",
    financialsCn: "收入修复取决于汽车/工业需求和长期供货协议。",
    aiRead: "Indirect AI exposure through power management, connectivity and specialty chips.",
    aiReadCn: "通过电源管理、连接和特色芯片间接受益 AI。",
    catalysts: ["Industrial recovery", "LTSA demand", "Specialty process wins"],
    catalystsCn: ["工业复苏", "长期协议需求", "特色工艺订单"],
    risks: ["Mature-node cyclicality", "Customer inventory", "Utilization"],
    risksCn: ["成熟制程周期", "客户库存", "产能利用率"],
    sourceIds: ["gfs-ir"]
  },
  {
    id: "umc",
    ticker: "UMC",
    company: "United Microelectronics",
    companyCn: "联华电子",
    market: "US/Taiwan",
    layer: "semicap",
    type: "Watchlist",
    conviction: "Medium",
    valuationRisk: "Medium",
    score: 71,
    role: "Mature-node foundry for specialty and mixed-signal chips.",
    roleCn: "成熟制程代工厂，服务特色与混合信号芯片。",
    lastReport: "2026-04-30",
    nextWindow: "Late Jul 2026, estimated",
    financials: "Utilization, ASPs and mature-node demand drive the earnings cycle.",
    financialsCn: "产能利用率、ASP 和成熟制程需求驱动盈利周期。",
    aiRead: "AI exposure is indirect but relevant through power, industrial and connectivity chips.",
    aiReadCn: "AI 暴露较间接，主要来自功率、工业和连接芯片。",
    catalysts: ["Utilization recovery", "Specialty process demand", "Taiwan supply-chain role"],
    catalystsCn: ["产能利用率恢复", "特色工艺需求", "台湾供应链角色"],
    risks: ["Mature-node oversupply", "Pricing pressure", "FX"],
    risksCn: ["成熟制程过剩", "价格压力", "汇率"],
    sourceIds: ["umc-ir"]
  },
  {
    id: "stm",
    ticker: "STM",
    company: "STMicroelectronics",
    companyCn: "意法半导体",
    market: "US/Europe",
    layer: "silicon",
    type: "Watchlist",
    conviction: "Medium",
    valuationRisk: "Medium",
    score: 72,
    role: "Industrial, automotive, power and embedded semiconductor supplier.",
    roleCn: "工业、汽车、功率与嵌入式半导体供应商。",
    lastReport: "2026-04-24",
    nextWindow: "Late Jul 2026, estimated",
    financials: "Near-term model depends on auto/industrial cycle stabilization.",
    financialsCn: "短期模型取决于汽车/工业周期稳定。",
    aiRead: "Edge AI, sensors and power semis matter, but this is not a pure AI infrastructure name.",
    aiReadCn: "边缘 AI、传感器和功率半导体重要，但不是纯 AI 基建标的。",
    catalysts: ["Industrial recovery", "Edge AI microcontrollers", "Power semis"],
    catalystsCn: ["工业复苏", "边缘 AI MCU", "功率半导体"],
    risks: ["Auto weakness", "Inventory correction", "China competition"],
    risksCn: ["汽车疲软", "库存调整", "中国竞争"],
    sourceIds: ["stm-ir"]
  },
  {
    id: "cohr",
    ticker: "COHR",
    company: "Coherent",
    companyCn: "Coherent",
    market: "US",
    layer: "datacenter",
    type: "Watchlist",
    conviction: "Medium",
    valuationRisk: "High",
    score: 79,
    role: "Optical components and lasers for data-center and communications infrastructure.",
    roleCn: "面向数据中心与通信基础设施的光器件和激光器。",
    lastReport: "2026-05-06",
    nextWindow: "Early Aug 2026, estimated",
    financials: "AI datacom demand and margin execution are central to the equity story.",
    financialsCn: "AI 数通需求和利润率执行是股票故事核心。",
    aiRead: "Optical bandwidth is a key scaling constraint in AI clusters.",
    aiReadCn: "光带宽是 AI 集群扩展的关键约束。",
    catalysts: ["800G/1.6T optics", "Datacom demand", "Margin recovery"],
    catalystsCn: ["800G/1.6T 光模块", "数通需求", "利润率恢复"],
    risks: ["Telecom weakness", "Execution", "Customer concentration"],
    risksCn: ["电信疲软", "执行", "客户集中度"],
    sourceIds: ["cohr-ir"]
  },
  {
    id: "lite",
    ticker: "LITE",
    company: "Lumentum",
    companyCn: "Lumentum",
    market: "US",
    layer: "datacenter",
    type: "Watchlist",
    conviction: "Medium",
    valuationRisk: "High",
    score: 74,
    role: "Optical and photonic components for cloud, datacom and telecom.",
    roleCn: "面向云、数通和电信的光学与光子组件。",
    lastReport: "2026-05-08",
    nextWindow: "Early Aug 2026, estimated",
    financials: "Datacom recovery and cost discipline are the main watch items.",
    financialsCn: "数通复苏和成本纪律是主要观察点。",
    aiRead: "Potential optical beneficiary if AI cluster bandwidth demand keeps accelerating.",
    aiReadCn: "若 AI 集群带宽需求持续加速，Lumentum 可能受益。",
    catalysts: ["Cloud optics demand", "Telecom stabilization", "Margin recovery"],
    catalystsCn: ["云光模块需求", "电信稳定", "利润率恢复"],
    risks: ["Cyclical demand", "Customer concentration", "Pricing"],
    risksCn: ["周期需求", "客户集中度", "定价"],
    sourceIds: ["lite-ir"]
  },
  {
    id: "csco",
    ticker: "CSCO",
    company: "Cisco Systems",
    companyCn: "思科",
    market: "US",
    layer: "datacenter",
    type: "Core",
    conviction: "Medium",
    valuationRisk: "Medium",
    score: 80,
    role: "Networking, security and observability platform for enterprises and cloud.",
    roleCn: "面向企业和云的网络、安全与可观测性平台。",
    lastReport: "2026-05-13",
    nextWindow: "Mid-Aug 2026, estimated",
    financials: "AI networking orders, Splunk integration and campus refresh are key metrics.",
    financialsCn: "AI 网络订单、Splunk 整合和园区网络更新是关键指标。",
    aiRead: "Less pure than Arista but a broader enterprise AI infrastructure beneficiary.",
    aiReadCn: "纯度低于 Arista，但企业 AI 基础设施暴露更广。",
    catalysts: ["AI networking orders", "Security platform", "Splunk cross-sell"],
    catalystsCn: ["AI 网络订单", "安全平台", "Splunk 交叉销售"],
    risks: ["Enterprise IT cycle", "Cloud share", "Integration"],
    risksCn: ["企业 IT 周期", "云份额", "整合"],
    sourceIds: ["csco-ir"]
  },
  {
    id: "cien",
    ticker: "CIEN",
    company: "Ciena",
    companyCn: "Ciena",
    market: "US",
    layer: "datacenter",
    type: "Watchlist",
    conviction: "Medium",
    valuationRisk: "High",
    score: 73,
    role: "Optical networking systems for carriers, cloud and data-center interconnect.",
    roleCn: "面向运营商、云和数据中心互联的光网络系统。",
    lastReport: "2026-06-05",
    nextWindow: "Early Sep 2026, estimated",
    financials: "Cloud and carrier optical spending drive the order cycle.",
    financialsCn: "云和运营商光网络支出驱动订单周期。",
    aiRead: "AI traffic growth increases long-haul and DCI bandwidth requirements.",
    aiReadCn: "AI 流量增长提升长距和数据中心互联带宽需求。",
    catalysts: ["Cloud optical demand", "DCI upgrade", "Carrier recovery"],
    catalystsCn: ["云光网络需求", "DCI 升级", "运营商复苏"],
    risks: ["Carrier capex cycles", "Customer concentration", "Gross margin volatility"],
    risksCn: ["运营商资本开支周期", "客户集中度", "毛利率波动"],
    sourceIds: ["cien-ir"]
  },
  {
    id: "eqix",
    ticker: "EQIX",
    company: "Equinix",
    companyCn: "Equinix",
    market: "US",
    layer: "cloud",
    type: "Core",
    conviction: "Medium",
    valuationRisk: "Medium",
    score: 81,
    role: "Global colocation and interconnection data-center platform.",
    roleCn: "全球托管与互联数据中心平台。",
    lastReport: "2026-04-29",
    nextWindow: "Late Jul 2026, estimated",
    financials: "Leasing, interconnection revenue and power availability drive the model.",
    financialsCn: "租赁、互联收入和电力可得性驱动模型。",
    aiRead: "AI expands demand for interconnected colocation, though power limits remain a constraint.",
    aiReadCn: "AI 扩大互联托管需求，但电力限制仍是约束。",
    catalysts: ["AI colocation demand", "Interconnection growth", "Power capacity"],
    catalystsCn: ["AI 托管需求", "互联增长", "电力容量"],
    risks: ["Interest rates", "Power constraints", "REIT valuation"],
    risksCn: ["利率", "电力约束", "REIT 估值"],
    sourceIds: ["eqix-ir"]
  },
  {
    id: "dlr",
    ticker: "DLR",
    company: "Digital Realty",
    companyCn: "Digital Realty",
    market: "US",
    layer: "cloud",
    type: "Core",
    conviction: "Medium",
    valuationRisk: "Medium",
    score: 79,
    role: "Global data-center REIT with hyperscale leasing exposure.",
    roleCn: "全球数据中心 REIT，具备超大云租赁暴露。",
    lastReport: "2026-04-24",
    nextWindow: "Late Jul 2026, estimated",
    financials: "Leasing spreads, development pipeline and cost of capital are key.",
    financialsCn: "租赁价差、开发管线和资本成本是关键。",
    aiRead: "AI demand supports data-center absorption and pricing, especially where power is scarce.",
    aiReadCn: "AI 需求支撑数据中心吸收和定价，尤其在电力稀缺区域。",
    catalysts: ["Hyperscale leasing", "Pricing power", "Development pipeline"],
    catalystsCn: ["超大云租赁", "定价权", "开发管线"],
    risks: ["Interest rates", "Development execution", "Tenant concentration"],
    risksCn: ["利率", "开发执行", "租户集中度"],
    sourceIds: ["dlr-ir"]
  },
  {
    id: "ibm",
    ticker: "IBM",
    company: "IBM",
    companyCn: "IBM",
    market: "US",
    layer: "software",
    type: "Core",
    conviction: "Medium",
    valuationRisk: "Medium",
    score: 78,
    role: "Hybrid cloud, enterprise AI consulting and watsonx platform.",
    roleCn: "混合云、企业 AI 咨询与 watsonx 平台。",
    lastReport: "2026-04-23",
    nextWindow: "Late Jul 2026, estimated",
    financials: "Software growth, consulting backlog and free cash flow are the main valuation anchors.",
    financialsCn: "软件增长、咨询积压订单和自由现金流是主要估值锚。",
    aiRead: "A pragmatic enterprise AI beneficiary rather than a frontier model leader.",
    aiReadCn: "务实型企业 AI 受益者，而非前沿模型领导者。",
    catalysts: ["watsonx adoption", "Red Hat growth", "Consulting AI backlog"],
    catalystsCn: ["watsonx 采用", "Red Hat 增长", "AI 咨询积压"],
    risks: ["Consulting cycle", "Legacy drag", "AI monetization proof"],
    risksCn: ["咨询周期", "传统业务拖累", "AI 变现验证"],
    sourceIds: ["ibm-ir"]
  },
  {
    id: "adbe",
    ticker: "ADBE",
    company: "Adobe",
    companyCn: "Adobe",
    market: "US",
    layer: "software",
    type: "Core",
    conviction: "Medium",
    valuationRisk: "Medium",
    score: 80,
    role: "Creative, document and marketing software with Firefly generative AI.",
    roleCn: "创意、文档和营销软件平台，拥有 Firefly 生成式 AI。",
    lastReport: "2026-03-12",
    nextWindow: "2026-06-12 announced",
    financials: "Creative Cloud and Document Cloud monetization remain the key indicators.",
    financialsCn: "Creative Cloud 和 Document Cloud 变现仍是关键指标。",
    aiRead: "Firefly must turn AI usage into ARPU and seat expansion to defend the multiple.",
    aiReadCn: "Firefly 需要把 AI 使用转化为 ARPU 和席位扩张，以支撑估值。",
    catalysts: ["Firefly monetization", "Creative Cloud growth", "Enterprise AI workflows"],
    catalystsCn: ["Firefly 变现", "Creative Cloud 增长", "企业 AI 工作流"],
    risks: ["Creative competition", "Seat pressure", "AI margin cost"],
    risksCn: ["创意软件竞争", "席位压力", "AI 成本"],
    sourceIds: ["adbe-ir"]
  },
  {
    id: "sap",
    ticker: "SAP",
    company: "SAP",
    companyCn: "SAP",
    market: "US/Europe",
    layer: "software",
    type: "Core",
    conviction: "Medium",
    valuationRisk: "Medium",
    score: 79,
    role: "ERP, enterprise workflows, cloud migration and embedded business AI.",
    roleCn: "ERP、企业工作流、云迁移与嵌入式业务 AI。",
    lastReport: "2026-04-22",
    nextWindow: "Late Jul 2026, estimated",
    financials: "Cloud backlog, S/4HANA migration and margin expansion drive valuation.",
    financialsCn: "云积压订单、S/4HANA 迁移和利润率扩张驱动估值。",
    aiRead: "Embedded AI inside mission-critical ERP can monetize more defensibly than standalone tools.",
    aiReadCn: "嵌入关键 ERP 流程的 AI，比独立工具更具防御性变现能力。",
    catalysts: ["Cloud backlog", "Business AI attach", "Margin expansion"],
    catalystsCn: ["云积压订单", "业务 AI 附加", "利润率扩张"],
    risks: ["European macro", "Migration complexity", "Premium multiple"],
    risksCn: ["欧洲宏观", "迁移复杂度", "高估值倍数"],
    sourceIds: ["sap-ir"]
  },
  {
    id: "baba",
    ticker: "BABA",
    company: "Alibaba",
    companyCn: "阿里巴巴",
    market: "US/China",
    layer: "cloud",
    type: "Core",
    conviction: "Medium",
    valuationRisk: "High",
    score: 78,
    role: "China cloud, ecommerce, Qwen models and AI infrastructure platform.",
    roleCn: "中国云、电商、通义千问模型和 AI 基础设施平台。",
    lastReport: "2026-05-15",
    nextWindow: "Mid-Aug 2026, estimated",
    financials: "Cloud growth, ecommerce margin and AI model adoption are the key indicators.",
    financialsCn: "云增长、电商利润率和 AI 模型采用是关键指标。",
    aiRead: "One of China's most important AI platforms, with valuation discounted by macro and geopolitics.",
    aiReadCn: "中国最重要的 AI 平台之一，但估值受宏观和地缘折价影响。",
    catalysts: ["Qwen adoption", "Cloud acceleration", "Shareholder returns"],
    catalystsCn: ["通义千问采用", "云加速", "股东回报"],
    risks: ["China macro", "Regulatory risk", "US-China restrictions"],
    risksCn: ["中国宏观", "监管风险", "中美限制"],
    sourceIds: ["baba-ir"]
  },
  {
    id: "bidu",
    ticker: "BIDU",
    company: "Baidu",
    companyCn: "百度",
    market: "US/China",
    layer: "software",
    type: "Watchlist",
    conviction: "Medium",
    valuationRisk: "High",
    score: 73,
    role: "China AI cloud, ERNIE models, search and autonomous driving.",
    roleCn: "中国 AI 云、文心模型、搜索和自动驾驶。",
    lastReport: "2026-05-21",
    nextWindow: "Mid-Aug 2026, estimated",
    financials: "AI cloud progress must offset search pressure and China macro sensitivity.",
    financialsCn: "AI 云进展需要抵消搜索压力和中国宏观敏感性。",
    aiRead: "A China AI platform with model, cloud and Apollo optionality, but lower global investor appetite.",
    aiReadCn: "具备模型、云和 Apollo 期权的中国 AI 平台，但全球投资者风险偏好较低。",
    catalysts: ["ERNIE adoption", "AI cloud growth", "Apollo monetization"],
    catalystsCn: ["文心采用", "AI 云增长", "Apollo 变现"],
    risks: ["Ad weakness", "Competition", "ADR/geopolitical discount"],
    risksCn: ["广告疲软", "竞争", "ADR/地缘折价"],
    sourceIds: ["bidu-ir"]
  }
];

sources.push(...additionalSources);
companies.push(...additionalCompanies);

Object.assign(companySectorOverrides, {
  CEG: ["power-grid"],
  VST: ["power-grid"],
  OKLO: ["power-grid"],
  BWXT: ["power-grid"],
  HUBB: ["power-grid"],
  FIX: ["power-grid", "servers-cooling"],
  INTC: ["compute-design", "foundry-packaging"],
  QCOM: ["compute-design", "physical-ai"],
  ALAB: ["networking-optics", "servers-cooling"],
  WDC: ["memory-storage"],
  STX: ["memory-storage"],
  GFS: ["foundry-packaging"],
  UMC: ["foundry-packaging"],
  STM: ["compute-design", "physical-ai"],
  COHR: ["networking-optics"],
  LITE: ["networking-optics"],
  CSCO: ["networking-optics", "ai-infra-software"],
  CIEN: ["networking-optics"],
  EQIX: ["cloud-ai-factory"],
  DLR: ["cloud-ai-factory"],
  IBM: ["ai-infra-software", "applications"],
  ADBE: ["applications"],
  SAP: ["applications"],
  BABA: ["cloud-ai-factory", "models", "applications"],
  BIDU: ["models", "applications", "physical-ai"]
});
